language: java
jdk:
  - oraclejdk11
  - openjdk11
sudo: false
notifications:
  email: false
after_success:
  - mvn clean test jacoco:report coveralls:report
before_install:
  - "cp travis-settings.xml $HOME/.m2/settings.xml"
deploy:
  provider: script
  script: mvn deploy;
  on:
    branch: master
    jdk: openjdk11
