name: Earthly CI

permissions:
  contents: read
  actions: read
  checks: write

on:
  push:
    branches: [ main ]
jobs:
  prod:
    name: Build
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: build
        run: earthly --ci --org sjerred --output +ci
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: castle-casters.jar
          path: castle-casters.jar
      - name: test
        run: earthly --ci --org sjerred --output +test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Tests
          path: surefire-reports/*.xml
          reporter: java-junit