name: Earthly CI

on:
  push:
    branches: [main]
jobs:
  prod:
    name: Build
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: earthly/actions-setup@v1.0.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: build
        run: earthly --ci --sat lamport --org sjerred +ci
